-- CMS 파일 상세 테이블 확장 (DAM 기능 지원)
ALTER TABLE CMS_FILE_DETAIL ADD COLUMN FILE_WIDTH INT COMMENT '이미지 너비';
ALTER TABLE CMS_FILE_DETAIL ADD COLUMN FILE_HEIGHT INT COMMENT '이미지 높이';
ALTER TABLE CMS_FILE_DETAIL ADD COLUMN FILE_TY VARCHAR(100) COMMENT 'MIME 타입 (image/jpeg 등)';
ALTER TABLE CMS_FILE_DETAIL ADD COLUMN AUTHOR VARCHAR(50) COMMENT '작성자/소유자';
ALTER TABLE CMS_FILE_DETAIL ADD COLUMN TAGS VARCHAR(500) COMMENT '태그 (콤마 구분)';

-- CMS 미디어 폴더 테이블 (계층형 구조)
CREATE TABLE IF NOT EXISTS CMS_MEDIA_FOLDER (
    FOLDER_ID VARCHAR(20) NOT NULL COMMENT '폴더 ID',
    UPPER_FOLDER_ID VARCHAR(20) COMMENT '상위 폴더 ID',
    FOLDER_NM VARCHAR(100) NOT NULL COMMENT '폴더 명',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    PRIMARY KEY (FOLDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 미디어 폴더 관리';

-- 파일 테이블에 폴더 ID 컬럼 추가
ALTER TABLE CMS_FILE_DETAIL ADD COLUMN FOLDER_ID VARCHAR(20) COMMENT '소속 폴더 ID';
