-- 1. 워크플로우 요청 테이블
CREATE TABLE IF NOT EXISTS CMS_WORKFLOW_REQUEST (
    REQ_ID              VARCHAR(20) NOT NULL COMMENT '요청 ID (WFRQ_...)',
    TARGET_ID           VARCHAR(20) NOT NULL COMMENT '대상 콘텐츠 ID (BBS_..., MENU_...)',
    TARGET_TYPE         VARCHAR(20) NOT NULL COMMENT '대상 유형 (ARTICLE, MENU, WIDGET)',
    REQ_USER_ID         VARCHAR(20) NOT NULL COMMENT '요청자 ID',
    REQ_DT              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '요청 일시',
    REQ_SJ              VARCHAR(200) NOT NULL COMMENT '요청 제목',
    REQ_CN              TEXT COMMENT '요청 내용 (변경 사유 등)',
    STATUS              VARCHAR(20) NOT NULL DEFAULT 'REQUESTED' COMMENT '상태 (REQUESTED, APPROVED, REJECTED, CANCELLED)',
    PROCESS_USER_ID     VARCHAR(20) COMMENT '처리자 ID',
    PROCESS_DT          DATETIME COMMENT '처리 일시',
    DATA_SNAPSHOT       LONGTEXT COMMENT '요청 시점 데이터 스냅샷 (JSON)',
    PRIMARY KEY (REQ_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='워크플로우 요청 관리';

-- 2. 워크플로우 이력 테이블
CREATE TABLE IF NOT EXISTS CMS_WORKFLOW_HISTORY (
    HIST_ID             INT AUTO_INCREMENT NOT NULL COMMENT '이력 ID',
    REQ_ID              VARCHAR(20) NOT NULL COMMENT '요청 ID',
    ACTION_CODE         VARCHAR(20) NOT NULL COMMENT '행동 코드 (REQUEST, APPROVE, REJECT)',
    ACTOR_ID            VARCHAR(20) NOT NULL COMMENT '행위자 ID',
    ACTION_DT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '행위 일시',
    ACTION_MSG          VARCHAR(500) COMMENT '행위 코멘트 (반려 사유 등)',
    PRIMARY KEY (HIST_ID),
    INDEX IDX_WF_HIST_REQ (REQ_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='워크플로우 처리 이력';
