USE nucms;

-- CMS 메뉴-역할 권한 테이블
CREATE TABLE IF NOT EXISTS CMS_MENU_ROLE (
    MENU_ID VARCHAR(20) NOT NULL COMMENT '메뉴 ID',
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드',
    PRIMARY KEY (MENU_ID, ROLE_CODE),
    FOREIGN KEY (MENU_ID) REFERENCES CMS_MENU(MENU_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_CODE) REFERENCES CMS_ROLE(ROLE_CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='역할별 메뉴 접근 권한';
