CREATE TABLE CMS_AUDIT_LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '로그ID',
    ACTION_TY VARCHAR(10) NOT NULL COMMENT '행위유형(INSERT, UPDATE, DELETE)',
    MENU_ID VARCHAR(20) COMMENT '대상메뉴ID',
    TARGET_ID VARCHAR(50) COMMENT '대상데이터ID',
    TARGET_NM VARCHAR(200) COMMENT '대상데이터명(제목 등)',
    BEFORE_VAL LONGTEXT COMMENT '변경전데이터(JSON)',
    AFTER_VAL LONGTEXT COMMENT '변경후데이터(JSON)',
    CLIENT_IP VARCHAR(50) COMMENT '요청IP',
    USER_ID VARCHAR(20) NOT NULL COMMENT '수행자ID',
    USER_NM VARCHAR(50) COMMENT '수행자명',
    CREAT_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '발생일시'
) COMMENT='통합 데이터 변경 감사 로그';

-- 인덱스 추가 (검색 속도 향상)
CREATE INDEX IX_CMS_AUDIT_LOG_01 ON CMS_AUDIT_LOG (USER_ID);
CREATE INDEX IX_CMS_AUDIT_LOG_02 ON CMS_AUDIT_LOG (ACTION_TY);
CREATE INDEX IX_CMS_AUDIT_LOG_03 ON CMS_AUDIT_LOG (CREAT_DT);
