CREATE TABLE CMS_SY_CONFIG (
    CONFIG_ID VARCHAR(20) NOT NULL COMMENT '설정ID',
    CONFIG_KEY VARCHAR(50) NOT NULL COMMENT '설정키',
    CONFIG_VAL TEXT COMMENT '설정값',
    CONFIG_DC VARCHAR(500) COMMENT '설정설명',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일시',
    FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
    LAST_UPDT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종수정일시',
    LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
    PRIMARY KEY (CONFIG_ID),
    UNIQUE KEY UQ_CMS_SY_CONFIG_KEY (CONFIG_KEY)
) COMMENT='시스템 환경설정';

-- 초기 데이터 삽입
INSERT INTO CMS_SY_CONFIG (CONFIG_ID, CONFIG_KEY, CONFIG_VAL, CONFIG_DC, USE_AT, FRST_REGISTER_ID) VALUES
('CFG_00000000000001', 'SITE_TITLE', 'nu-CMS Enterprise', '사이트 제목', 'Y', 'admin'),
('CFG_00000000000002', 'SITE_COPYRIGHT', '© 2026 nu-CMS. All Rights Reserved.', '카피라이트 문구', 'Y', 'admin'),
('CFG_00000000000003', 'ADMIN_EMAIL', 'admin@nucms.com', '관리자 대표 이메일', 'Y', 'admin'),
('CFG_00000000000004', 'THEME_COLOR', '#1677ff', '메인 테마 컬러', 'Y', 'admin');
