USE nucms;

-- 5. CMS 회원 테이블
CREATE TABLE IF NOT EXISTS CMS_MEMBER (
    ESNTL_ID VARCHAR(20) NOT NULL COMMENT '고유 ID',
    MBER_ID VARCHAR(20) NOT NULL COMMENT '회원 ID',
    MBER_NM VARCHAR(60) NOT NULL COMMENT '회원 성명',
    PASSWORD VARCHAR(200) NOT NULL COMMENT '비밀번호 (암호화)',
    EMAIL_ADRES VARCHAR(50) COMMENT '이메일 주소',
    MBTLNUM VARCHAR(20) COMMENT '휴대폰 번호',
    MBER_STTUS_CODE CHAR(1) DEFAULT 'A' COMMENT '회원 상태 (A:정상, P:잠금, D:탈퇴, R:승인대기)',
    DI_KEY VARCHAR(100) COMMENT '본인인증 DI 값',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 가입 시점',
    LAST_UPDT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 시점',
    PRIMARY KEY (ESNTL_ID),
    UNIQUE KEY UQ_MBER_ID (MBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 회원 관리';

-- 6. CMS 역할(권한) 테이블
CREATE TABLE IF NOT EXISTS CMS_ROLE (
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드 (예: ROLE_ADMIN)',
    ROLE_NM VARCHAR(60) NOT NULL COMMENT '역할 명',
    ROLE_DC VARCHAR(200) COMMENT '역할 설명',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (ROLE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 역할 관리';

-- 7. CMS 회원-역할 매핑 테이블
CREATE TABLE IF NOT EXISTS CMS_MEMBER_ROLE (
    ESNTL_ID VARCHAR(20) NOT NULL COMMENT '회원 고유 ID',
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드',
    PRIMARY KEY (ESNTL_ID, ROLE_CODE),
    FOREIGN KEY (ESNTL_ID) REFERENCES CMS_MEMBER(ESNTL_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_CODE) REFERENCES CMS_ROLE(ROLE_CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 회원 권한 매핑';

-- 초기 데이터: 역할 (ROLE_ADMIN, ROLE_USER)
INSERT IGNORE INTO CMS_ROLE (ROLE_CODE, ROLE_NM, ROLE_DC) VALUES 
('ROLE_ADMIN', '시스템 관리자', '전체 시스템 관리 권한'),
('ROLE_USER', '일반 사용자', '일반적인 조회 및 글쓰기 권한');

-- 초기 데이터: 관리자 계정 (admin / admin - schema_cms.sql 참조 해시 사용)
INSERT IGNORE INTO CMS_MEMBER (ESNTL_ID, MBER_ID, MBER_NM, PASSWORD, EMAIL_ADRES, MBER_STTUS_CODE) 
VALUES ('USR_0000000000001', 'admin', '최고 관리자', '$2a$10$7zB3pS.Hq.M8D.G9w7D9e.nS8W5WqWnN3B8zE7fWnQzE7fWnQzE7f', 'admin@nucms.com', 'A');

-- 관리자 권한 부여
INSERT IGNORE INTO CMS_MEMBER_ROLE (ESNTL_ID, ROLE_CODE) VALUES ('USR_0000000000001', 'ROLE_ADMIN');
