CREATE TABLE `CMS_CATEGORY` (
  `CTGRY_ID` varchar(20) NOT NULL COMMENT '카테고리ID',
  `CTGRY_NM` varchar(100) NOT NULL COMMENT '카테고리명',
  `UPPER_CTGRY_ID` varchar(20) DEFAULT NULL COMMENT '상위카테고리ID',
  `USE_AT` char(1) DEFAULT 'Y' COMMENT '사용여부',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  PRIMARY KEY (`CTGRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='콘텐츠 카테고리';
