USE nucms;

-- [최종 종합 복구 스크립트]
-- 이 스크립트는 CMS 구동에 필요한 모든 테이블과 컬럼을 점검하고 복구합니다.
-- 에러가 발생해도 무시하고 끝까지 실행해주세요 (이미 존재하는 컬럼/테이블 에러일 수 있습니다).

-- -----------------------------------------------------
-- 1. 위젯 (CMS_WIDGET)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CMS_WIDGET (
    WIDGET_ID VARCHAR(20) NOT NULL,
    PRIMARY KEY (WIDGET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 컬럼 추가 (이미 있으면 에러나고 무시됨)
ALTER TABLE CMS_WIDGET ADD COLUMN WIDGET_NM VARCHAR(100) NOT NULL COMMENT '위젯 명';
ALTER TABLE CMS_WIDGET ADD COLUMN WIDGET_TY_CODE VARCHAR(10) NOT NULL COMMENT '위젯 유형';
ALTER TABLE CMS_WIDGET ADD COLUMN WIDGET_CN LONGTEXT COMMENT '위젯 설정';
ALTER TABLE CMS_WIDGET ADD COLUMN USE_AT CHAR(1) DEFAULT 'Y';
ALTER TABLE CMS_WIDGET ADD COLUMN FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP;

-- -----------------------------------------------------
-- 2. 템플릿 (CMS_TEMPLATE)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CMS_TEMPLATE (
    TMPLAT_ID VARCHAR(20) NOT NULL,
    PRIMARY KEY (TMPLAT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE CMS_TEMPLATE ADD COLUMN TMPLAT_NM VARCHAR(100) NOT NULL COMMENT '템플릿 명';
ALTER TABLE CMS_TEMPLATE ADD COLUMN TMPLAT_SE_CODE VARCHAR(10) COMMENT '구분 코드';
ALTER TABLE CMS_TEMPLATE ADD COLUMN TMPLAT_COURS VARCHAR(200) COMMENT '경로';
ALTER TABLE CMS_TEMPLATE ADD COLUMN USE_AT CHAR(1) DEFAULT 'Y';
ALTER TABLE CMS_TEMPLATE ADD COLUMN FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP;

-- -----------------------------------------------------
-- 3. 레이아웃 설정 (CMS_LAYOUT_CONFIG)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CMS_LAYOUT_CONFIG (
    CONFIG_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CONFIG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE CMS_LAYOUT_CONFIG ADD COLUMN TMPLAT_ID VARCHAR(20) NOT NULL COMMENT '템플릿 ID';
ALTER TABLE CMS_LAYOUT_CONFIG ADD COLUMN AREA_NM VARCHAR(50) NOT NULL COMMENT '영역 명';
ALTER TABLE CMS_LAYOUT_CONFIG ADD COLUMN WIDGET_ID VARCHAR(20) COMMENT '할당된 위젯 ID';
ALTER TABLE CMS_LAYOUT_CONFIG ADD COLUMN EXPSR_ORDR INT DEFAULT 0;

-- -----------------------------------------------------
-- 4. 메뉴 (CMS_MENU)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CMS_MENU (
    MENU_ID VARCHAR(20) NOT NULL,
    PRIMARY KEY (MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE CMS_MENU ADD COLUMN UPPER_MENU_ID VARCHAR(20);
ALTER TABLE CMS_MENU ADD COLUMN MENU_NM VARCHAR(100) NOT NULL;
ALTER TABLE CMS_MENU ADD COLUMN MENU_LVL INT DEFAULT 1;
ALTER TABLE CMS_MENU ADD COLUMN MENU_TY_CODE VARCHAR(10) DEFAULT 'CONT';
ALTER TABLE CMS_MENU ADD COLUMN CONECT_URL VARCHAR(255);
ALTER TABLE CMS_MENU ADD COLUMN EXPSR_ORDR INT DEFAULT 0;
ALTER TABLE CMS_MENU ADD COLUMN USE_AT CHAR(1) DEFAULT 'Y';

-- -----------------------------------------------------
-- 5. 샘플 데이터 복구
-- -----------------------------------------------------
INSERT IGNORE INTO CMS_TEMPLATE (TMPLAT_ID, TMPLAT_NM, TMPLAT_SE_CODE, TMPLAT_COURS)
VALUES ('TMPL_DEFAULT', '기본 반응형 템플릿', 'GENERAL', '/templates/general/default.html');

INSERT IGNORE INTO CMS_WIDGET (WIDGET_ID, WIDGET_NM, WIDGET_TY_CODE, WIDGET_CN, USE_AT)
VALUES ('WIDG_SAMPLE_01', '메인 배너', 'BANNER', '{"img":"/images/banner1.jpg"}', 'Y');
