USE nucms;

-- [위젯, 템플릿, 레이아웃] 테이블 컬럼 보정 스크립트
-- 기존 테이블이 존재하지만 컬럼이 누락된 경우를 위해 ALTER 문을 실행합니다.
-- "Duplicate column name" 에러가 발생하면 성공/이미 존재함으로 간주하고 무시하세요.

-- 1. CMS_WIDGET (위젯) 컬럼 추가
ALTER TABLE CMS_WIDGET ADD COLUMN WIDGET_TY_CODE VARCHAR(10) NOT NULL COMMENT '위젯 유형(BANNER, POPUP, QUICK)';
ALTER TABLE CMS_WIDGET ADD COLUMN WIDGET_CN LONGTEXT COMMENT '위젯 설정/콘텐츠(JSON 등)';
ALTER TABLE CMS_WIDGET ADD COLUMN USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부';
ALTER TABLE CMS_WIDGET ADD COLUMN FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점';

-- 2. CMS_TEMPLATE (템플릿) 컬럼 추가
ALTER TABLE CMS_TEMPLATE ADD COLUMN TMPLAT_SE_CODE VARCHAR(10) COMMENT '템플릿 구분 코드';
ALTER TABLE CMS_TEMPLATE ADD COLUMN TMPLAT_COURS VARCHAR(200) COMMENT '템플릿 경로';
ALTER TABLE CMS_TEMPLATE ADD COLUMN USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부';
ALTER TABLE CMS_TEMPLATE ADD COLUMN FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점';

-- 3. CMS_LAYOUT_CONFIG (레이아웃 설정) 컬럼 추가
-- 이 테이블은 아예 없을 가능성이 높으므로 CREATE 문도 함께 넣습니다.
CREATE TABLE IF NOT EXISTS CMS_LAYOUT_CONFIG (
    CONFIG_ID INT NOT NULL AUTO_INCREMENT COMMENT '설정 ID',
    TMPLAT_ID VARCHAR(20) NOT NULL COMMENT '템플릿 ID',
    AREA_NM VARCHAR(50) NOT NULL COMMENT '영역 명',
    WIDGET_ID VARCHAR(20) COMMENT '할당된 위젯 ID',
    EXPSR_ORDR INT DEFAULT 0 COMMENT '영역 내 노출 순서',
    PRIMARY KEY (CONFIG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 레이아웃 영역별 위젯 설정';

-- 혹시 몰라 컬럼 추가도 (이미 있으면 에러나고 무시됨)
ALTER TABLE CMS_LAYOUT_CONFIG ADD COLUMN TMPLAT_ID VARCHAR(20) NOT NULL COMMENT '템플릿 ID';
ALTER TABLE CMS_LAYOUT_CONFIG ADD COLUMN AREA_NM VARCHAR(50) NOT NULL COMMENT '영역 명';
ALTER TABLE CMS_LAYOUT_CONFIG ADD COLUMN WIDGET_ID VARCHAR(20) COMMENT '할당된 위젯 ID';
ALTER TABLE CMS_LAYOUT_CONFIG ADD COLUMN EXPSR_ORDR INT DEFAULT 0 COMMENT '영역 내 노출 순서';

-- 샘플 템플릿 데이터 복구 (없을 경우에만)
INSERT IGNORE INTO CMS_TEMPLATE (TMPLAT_ID, TMPLAT_NM, TMPLAT_SE_CODE, TMPLAT_COURS)
VALUES ('TMPL_DEFAULT', '기본 반응형 템플릿', 'GENERAL', '/templates/general/default.html');
