USE nucms;

-- [통합] 누락된 테이블 생성 스크립트 (최종본)
-- 위젯, 템플릿, 레이아웃 설정 테이블이 포함되어 있습니다.

-- 1. CMS 위젯 테이블
CREATE TABLE IF NOT EXISTS CMS_WIDGET (
    WIDGET_ID VARCHAR(20) NOT NULL COMMENT '위젯 ID',
    WIDGET_NM VARCHAR(100) NOT NULL COMMENT '위젯 명',
    WIDGET_TY_CODE VARCHAR(10) NOT NULL COMMENT '위젯 유형(BANNER, POPUP, QUICK)',
    WIDGET_CN LONGTEXT COMMENT '위젯 설정/콘텐츠(JSON 등)',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (WIDGET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 위젯 관리';

-- 2. CMS 템플릿 관리 테이블
CREATE TABLE IF NOT EXISTS CMS_TEMPLATE (
    TMPLAT_ID VARCHAR(20) NOT NULL COMMENT '템플릿 ID',
    TMPLAT_NM VARCHAR(100) NOT NULL COMMENT '템플릿 명',
    TMPLAT_SE_CODE VARCHAR(10) COMMENT '템플릿 구분 코드',
    TMPLAT_COURS VARCHAR(200) COMMENT '템플릿 경로',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (TMPLAT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 템플릿 관리';

-- 3. CMS 레이아웃 설정 테이블 (템플릿-위젯 매핑)
CREATE TABLE IF NOT EXISTS CMS_LAYOUT_CONFIG (
    CONFIG_ID INT NOT NULL AUTO_INCREMENT COMMENT '설정 ID',
    TMPLAT_ID VARCHAR(20) NOT NULL COMMENT '템플릿 ID',
    AREA_NM VARCHAR(50) NOT NULL COMMENT '영역 명(Header, Footer, Sidebar 등)',
    WIDGET_ID VARCHAR(20) COMMENT '할당된 위젯 ID',
    EXPSR_ORDR INT DEFAULT 0 COMMENT '영역 내 노출 순서',
    PRIMARY KEY (CONFIG_ID),
    FOREIGN KEY (TMPLAT_ID) REFERENCES CMS_TEMPLATE(TMPLAT_ID) ON DELETE CASCADE,
    FOREIGN KEY (WIDGET_ID) REFERENCES CMS_WIDGET(WIDGET_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 레이아웃 영역별 위젯 설정';

-- 4. CMS 메뉴 테이블 (컬럼 확인용)
CREATE TABLE IF NOT EXISTS CMS_MENU (
    MENU_ID VARCHAR(20) NOT NULL COMMENT '메뉴 ID',
    UPPER_MENU_ID VARCHAR(20) COMMENT '부모 메뉴 ID',
    MENU_NM VARCHAR(100) NOT NULL COMMENT '메뉴명',
    MENU_LVL INT DEFAULT 1 COMMENT '메뉴 레벨',
    MENU_TY_CODE VARCHAR(10) DEFAULT 'CONT' COMMENT '메뉴 유형',
    CONECT_URL VARCHAR(255) COMMENT '연결 URL',
    EXPSR_ORDR INT NOT NULL DEFAULT 0 COMMENT '노출 순서',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    PRIMARY KEY (MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 메뉴 관리';


-- [기존 테이블 재생성용 - 이미 있으면 무시됨]
CREATE TABLE IF NOT EXISTS CMS_ACCESS_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
    ESNTL_ID VARCHAR(20),
    CONECT_IP VARCHAR(50),
    CONECT_METHOD VARCHAR(10),
    CONECT_URL VARCHAR(255),
    LOG_CN LONGTEXT,
    CREAT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 초기 샘플 데이터 (기본 템플릿)
INSERT IGNORE INTO CMS_TEMPLATE (TMPLAT_ID, TMPLAT_NM, TMPLAT_SE_CODE, TMPLAT_COURS)
VALUES ('TMPL_DEFAULT', '기본 반응형 템플릿', 'GENERAL', '/templates/general/default.html');
