USE nucms;

-- [게시판 관리] 누락된 테이블 생성 및 컬럼 보정 스크립트

-- 1. 게시판 마스터 테이블 (CMS_BOARD_MASTER)
CREATE TABLE IF NOT EXISTS CMS_BOARD_MASTER (
    BBS_ID VARCHAR(20) NOT NULL COMMENT '게시판 ID',
    BBS_NM VARCHAR(100) NOT NULL COMMENT '게시판 명',
    BBS_INTRCN VARCHAR(500) COMMENT '게시판 소개',
    BBS_TY_CODE VARCHAR(20) NOT NULL COMMENT '게시판 유형 코드(BBST01:일반, BBST02:공지)',
    REPLY_POSBL_AT CHAR(1) DEFAULT 'N' COMMENT '답글 가능 여부',
    FILE_ATCH_POSBL_AT CHAR(1) DEFAULT 'Y' COMMENT '파일 첨부 가능 여부',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (BBS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 게시판 마스터';

-- 2. 게시물 테이블 (CMS_BOARD_POST)
CREATE TABLE IF NOT EXISTS CMS_BOARD_POST (
    NTT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '게시물 ID',
    BBS_ID VARCHAR(20) NOT NULL COMMENT '게시판 ID',
    NTT_SJ VARCHAR(200) NOT NULL COMMENT '게시물 제목',
    NTT_CN LONGTEXT COMMENT '게시물 내용',
    RDCNT INT DEFAULT 0 COMMENT '조회수',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    ATCH_FILE_ID VARCHAR(20) COMMENT '첨부파일 ID',
    FRST_REGISTER_ID VARCHAR(20) COMMENT '최초 등록자 ID',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    LAST_UPDT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 시점',
    PRIMARY KEY (NTT_ID),
    FOREIGN KEY (BBS_ID) REFERENCES CMS_BOARD_MASTER(BBS_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 게시판 게시물';

-- 3. 게시판 댓글/답글 테이블 (선택 사항, 추후 확장)
-- CREATE TABLE IF NOT EXISTS CMS_BOARD_COMMENT ...

-- 초기 샘플 데이터: 공지사항 게시판
INSERT IGNORE INTO CMS_BOARD_MASTER (BBS_ID, BBS_NM, BBS_INTRCN, BBS_TY_CODE, USE_AT)
VALUES ('BBSMSTR_AAAAAAAAAAAA', '공지사항', '시스템 공지사항 게시판입니다.', 'BBST02', 'Y');

-- 초기 샘플 데이터: 자유게시판
INSERT IGNORE INTO CMS_BOARD_MASTER (BBS_ID, BBS_NM, BBS_INTRCN, BBS_TY_CODE, USE_AT)
VALUES ('BBSMSTR_BBBBBBBBBBBB', '자유게시판', '자유롭게 글을 쓸 수 있는 공간입니다.', 'BBST01', 'Y');
