USE nucms;

-- CMS_CONTENT_HIST 테이블 생성 (콘텐츠 이력 관리)
CREATE TABLE IF NOT EXISTS CMS_CONTENT_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력 ID',
    CNTENTS_ID VARCHAR(20) NOT NULL COMMENT '콘텐츠 ID',
    SJ VARCHAR(200) NOT NULL COMMENT '제목',
    CN LONGTEXT COMMENT '내용',
    WRTER_ID VARCHAR(20) COMMENT '작성자 ID',
    STTUS_CODE VARCHAR(10) DEFAULT 'I' COMMENT '상태 코드',
    VER_NO INT DEFAULT 1 COMMENT '버전 번호',
    TMPLAT_ID VARCHAR(20) COMMENT '템플릿 ID',
    UPDT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '수정/아카이빙 일시',
    PRIMARY KEY (HIST_ID),
    INDEX IDX_CMS_CONTENT_HIST_01 (CNTENTS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 콘텐츠 변경 이력';

-- 확인용 조회
DESC CMS_CONTENT_HIST;
