USE nucms;

-- CMS_CONTENT 테이블에 누락된 게시 기간 컬럼 추가
ALTER TABLE CMS_CONTENT
ADD COLUMN NTCE_BGNDE DATETIME NULL COMMENT '게시 시작 일시',
ADD COLUMN NTCE_ENDDE DATETIME NULL COMMENT '게시 종료 일시';

-- 확인용 조회
DESC CMS_CONTENT;
