USE nucms;

-- [회원 및 역할 관리] 누락된 테이블 생성 및 컬럼 보정 스크립트

-- 1. 회원 테이블 (CMS_MEMBER)
CREATE TABLE IF NOT EXISTS CMS_MEMBER (
    ESNTL_ID VARCHAR(20) NOT NULL COMMENT '고유 ID',
    MBER_ID VARCHAR(20) NOT NULL COMMENT '회원 ID',
    MBER_NM VARCHAR(50) NOT NULL COMMENT '회원 명',
    PASSWORD VARCHAR(200) NOT NULL COMMENT '비밀번호 (암호화)',
    EMAIL_ADRES VARCHAR(100) COMMENT '이메일 주소',
    MBTLNUM VARCHAR(20) COMMENT '휴대폰 번호',
    MBER_STTUS_CODE VARCHAR(10) DEFAULT 'A' COMMENT '회원 상태 (A:정상, P:잠금, D:탈퇴)',
    DI_KEY VARCHAR(100) COMMENT '본인인증 키',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '가입일',
    LAST_UPDT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    PRIMARY KEY (ESNTL_ID),
    UNIQUE KEY (MBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 회원 관리';

-- 2. 역할 정보 테이블 (CMS_ROLE)
CREATE TABLE IF NOT EXISTS CMS_ROLE (
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드',
    ROLE_NM VARCHAR(50) NOT NULL COMMENT '역할 명',
    ROLE_DC VARCHAR(200) COMMENT '역할 설명',
    USE_AT CHAR(1) DEFAULT 'Y',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 역할 정보';

-- 3. 회원-역할 매핑 테이블 (CMS_MEMBER_ROLE)
CREATE TABLE IF NOT EXISTS CMS_MEMBER_ROLE (
    ESNTL_ID VARCHAR(20) NOT NULL COMMENT '회원 고유 ID',
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드',
    PRIMARY KEY (ESNTL_ID, ROLE_CODE),
    FOREIGN KEY (ESNTL_ID) REFERENCES CMS_MEMBER(ESNTL_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_CODE) REFERENCES CMS_ROLE(ROLE_CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 회원 역할 매핑';

-- 4. 역할-메뉴 권한 매핑 테이블 (CMS_ROLE_MENU)
CREATE TABLE IF NOT EXISTS CMS_ROLE_MENU (
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드',
    MENU_ID VARCHAR(20) NOT NULL COMMENT '메뉴 ID',
    PRIMARY KEY (ROLE_CODE, MENU_ID),
    FOREIGN KEY (ROLE_CODE) REFERENCES CMS_ROLE(ROLE_CODE) ON DELETE CASCADE,
    FOREIGN KEY (MENU_ID) REFERENCES CMS_MENU(MENU_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 역할별 메뉴 접근 권한';

-- 초기 관리자 계정 생성 (없을 경우)
INSERT IGNORE INTO CMS_MEMBER (ESNTL_ID, MBER_ID, MBER_NM, PASSWORD, MBER_STTUS_CODE)
VALUES ('ADMIN_0000001', 'admin', '최고관리자', '{noop}admin123', 'A');

-- 초기 관리자 역할 생성
INSERT IGNORE INTO CMS_ROLE (ROLE_CODE, ROLE_NM, ROLE_DC)
VALUES ('ROLE_ADMIN', '시스템 관리자', '모든 권한을 가진 관리자');

-- 관리자 계정에 관리자 역할 부여
INSERT IGNORE INTO CMS_MEMBER_ROLE (ESNTL_ID, ROLE_CODE)
VALUES ('ADMIN_0000001', 'ROLE_ADMIN');
