@echo off
echo Check CMS_SY_CONFIG...
"C:\Program Files\MariaDB 11.4\bin\mariadb.exe" -u root -p1234 nu_cms -e "SHOW TABLES LIKE 'CMS_SY_CONFIG';"
echo Check CMS_AUDIT_LOG...
"C:\Program Files\MariaDB 11.4\bin\mariadb.exe" -u root -p1234 nu_cms -e "SHOW TABLES LIKE 'CMS_AUDIT_LOG';"
