USE nucms;

-- CMS 콘텐츠 테이블
CREATE TABLE CMS_CONTENT (
    CNTENTS_ID VARCHAR(20) NOT NULL COMMENT '콘텐츠 ID',
    SJ VARCHAR(255) NOT NULL COMMENT '제목',
    CN LONGTEXT COMMENT '본문',
    WRTER_ID VARCHAR(20) NOT NULL COMMENT '작성자 ID',
    STTUS_CODE CHAR(1) NOT NULL DEFAULT 'I' COMMENT '상태(I:임시, R:검토, A:승인, P:게시, D:종료)',
    VER_NO INT NOT NULL DEFAULT 1 COMMENT '버전 번호',
    TMPLAT_ID VARCHAR(20) COMMENT '적용 템플릿 ID',
    CTGRY_ID VARCHAR(20) COMMENT '카테고리 ID',
    NTCE_BGNDE DATETIME COMMENT '게시 시작 일시',
    NTCE_ENDDE DATETIME COMMENT '게시 종료 일시',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록시점',
    LAST_UPDT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종수정시점',
    PRIMARY KEY (CNTENTS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 콘텐츠 관리';

-- CMS 카테고리 테이블
CREATE TABLE CMS_CATEGORY (
    CTGRY_ID VARCHAR(20) NOT NULL COMMENT '카테고리 ID',
    UPPER_CTGRY_ID VARCHAR(20) COMMENT '상위 카테고리 ID',
    CTGRY_NM VARCHAR(100) NOT NULL COMMENT '카테고리명',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    PRIMARY KEY (CTGRY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 카테고리 관리';

-- CMS 태그 테이블
CREATE TABLE CMS_TAG (
    TAG_ID VARCHAR(20) NOT NULL COMMENT '태그 ID',
    TAG_NM VARCHAR(50) NOT NULL COMMENT '태그명',
    PRIMARY KEY (TAG_ID),
    UNIQUE INDEX (TAG_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 태그 관리';

-- CMS 콘텐츠-태그 매핑 테이블
CREATE TABLE CMS_CONTENT_TAG_MAP (
    CNTENTS_ID VARCHAR(20) NOT NULL COMMENT '콘텐츠 ID',
    TAG_ID VARCHAR(20) NOT NULL COMMENT '태그 ID',
    PRIMARY KEY (CNTENTS_ID, TAG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 콘텐츠-태그 매핑';

-- CMS 워크플로우 로그 테이블
CREATE TABLE CMS_WORKFLOW_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '로그 ID',
    CNTENTS_ID VARCHAR(20) NOT NULL COMMENT '콘텐츠 ID',
    PRE_STTUS_CODE CHAR(1) COMMENT '이전 상태 코드',
    AFT_STTUS_CODE CHAR(1) NOT NULL COMMENT '변경 상태 코드',
    PROCR_ID VARCHAR(20) NOT NULL COMMENT '처리기 ID',
    PROCESS_CN VARCHAR(1000) COMMENT '처리 내용',
    PROCESS_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '처리 시점',
    PRIMARY KEY (LOG_ID),
    INDEX (CNTENTS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 워크플로우 결재 이력';

-- CMS 메뉴 테이블
CREATE TABLE CMS_MENU (
    MENU_ID VARCHAR(20) NOT NULL COMMENT '메뉴 ID',
    UPPER_MENU_ID VARCHAR(20) COMMENT '부모 메뉴 ID',
    MENU_NM VARCHAR(100) NOT NULL COMMENT '메뉴명',
    MENU_LVL INT DEFAULT 1 COMMENT '메뉴 레벨',
    MENU_TY_CODE VARCHAR(10) DEFAULT 'CONT' COMMENT '메뉴 유형(LINK, CONT, WIDG)',
    CONECT_URL VARCHAR(255) COMMENT '연결 URL',
    EXPSR_ORDR INT NOT NULL DEFAULT 0 COMMENT '노출 순서',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    PRIMARY KEY (MENU_ID),
    FOREIGN KEY (UPPER_MENU_ID) REFERENCES CMS_MENU(MENU_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 메뉴 관리';

-- CMS 위젯 테이블
CREATE TABLE CMS_WIDGET (
    WIDGET_ID VARCHAR(20) NOT NULL COMMENT '위젯 ID',
    WIDGET_NM VARCHAR(100) NOT NULL COMMENT '위젯 명',
    WIDGET_TY_CODE VARCHAR(10) NOT NULL COMMENT '위젯 유형(BANNER, POPUP, QUICK)',
    WIDGET_CN LONGTEXT COMMENT '위젯 설정/콘텐츠(JSON 등)',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (WIDGET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 위젯 관리';

-- CMS 레이아웃 설정 테이블
CREATE TABLE CMS_LAYOUT_CONFIG (
    CONFIG_ID INT NOT NULL AUTO_INCREMENT COMMENT '설정 ID',
    TMPLAT_ID VARCHAR(20) NOT NULL COMMENT '템플릿 ID',
    AREA_NM VARCHAR(50) NOT NULL COMMENT '영역 명(Header, Footer, Sidebar 등)',
    WIDGET_ID VARCHAR(20) COMMENT '할당된 위젯 ID',
    EXPSR_ORDR INT DEFAULT 0 COMMENT '영역 내 노출 순서',
    PRIMARY KEY (CONFIG_ID),
    FOREIGN KEY (TMPLAT_ID) REFERENCES CMS_TEMPLATE(TMPLAT_ID),
    FOREIGN KEY (WIDGET_ID) REFERENCES CMS_WIDGET(WIDGET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 레이아웃 영역별 위젯 설정';

-- CMS 콘텐츠 이력(아카이빙) 테이블
CREATE TABLE CMS_CONTENT_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력 ID',
    CNTENTS_ID VARCHAR(20) NOT NULL COMMENT '콘텐츠 ID',
    SJ VARCHAR(255) NOT NULL COMMENT '제목',
    CN LONGTEXT COMMENT '본문',
    WRTER_ID VARCHAR(20) NOT NULL COMMENT '작성자 ID',
    STTUS_CODE CHAR(1) NOT NULL COMMENT '상태 코드',
    VER_NO INT NOT NULL COMMENT '버전 번호',
    TMPLAT_ID VARCHAR(20) COMMENT '적용 템플릿 ID',
    UPDT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '수정 시점',
    PRIMARY KEY (HIST_ID),
    INDEX (CNTENTS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 콘텐츠 버전 관리 아카이빙';

-- CMS 템플릿 관리 테이블
CREATE TABLE CMS_TEMPLATE (
    TMPLAT_ID VARCHAR(20) NOT NULL COMMENT '템플릿 ID',
    TMPLAT_NM VARCHAR(100) NOT NULL COMMENT '템플릿 명',
    TMPLAT_SE_CODE VARCHAR(10) COMMENT '템플릿 구분 코드',
    TMPLAT_COURS VARCHAR(200) COMMENT '템플릿 경로',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (TMPLAT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 템플릿 관리';

-- 기본 템플릿 샘플 데이터
INSERT INTO CMS_TEMPLATE (TMPLAT_ID, TMPLAT_NM, TMPLAT_SE_CODE, TMPLAT_COURS)
VALUES ('TMPL_DEFAULT', '기본 반응형 템플릿', 'GENERAL', '/templates/general/default.html');
INSERT INTO CMS_TEMPLATE (TMPLAT_ID, TMPLAT_NM, TMPLAT_SE_CODE, TMPLAT_COURS)
VALUES ('TMPL_BLOG', '블로그형 템플릿', 'BLOG', '/templates/blog/main.html');

-- CMS 역할(권한) 테이블
CREATE TABLE CMS_ROLE (
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드',
    ROLE_NM VARCHAR(50) NOT NULL COMMENT '역할 명',
    ROLE_DC VARCHAR(500) COMMENT '역할 설명',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (ROLE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 역할 관리';

-- CMS 회원 테이블
CREATE TABLE CMS_MEMBER (
    ESNTL_ID VARCHAR(20) NOT NULL COMMENT '고유 ID',
    MBER_ID VARCHAR(20) NOT NULL COMMENT '회원 ID',
    MBER_NM VARCHAR(50) NOT NULL COMMENT '회원 명',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '비밀번호',
    EMAIL_ADRES VARCHAR(100) COMMENT '이메일 주소',
    MBTLNUM VARCHAR(20) COMMENT '휴대폰 번호',
    MBER_STTUS_CODE CHAR(1) DEFAULT 'A' COMMENT '상태(A:정상, P:잠금, D:탈퇴, R:승인대기)',
    DI_KEY VARCHAR(100) COMMENT '본인인증 DI',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '가입 시점',
    LAST_UPDT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 시점',
    PRIMARY KEY (ESNTL_ID),
    UNIQUE INDEX (MBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 회원 관리';

-- CMS 회원-역할 매핑 테이블
CREATE TABLE CMS_MEMBER_ROLE (
    ESNTL_ID VARCHAR(20) NOT NULL COMMENT '내부 고유 ID',
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드',
    PRIMARY KEY (ESNTL_ID, ROLE_CODE),
    FOREIGN KEY (ESNTL_ID) REFERENCES CMS_MEMBER(ESNTL_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_CODE) REFERENCES CMS_ROLE(ROLE_CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 회원별 역할 배정';

-- CMS 메뉴-역할 권한 테이블
CREATE TABLE CMS_MENU_ROLE (
    MENU_ID VARCHAR(20) NOT NULL COMMENT '메뉴 ID',
    ROLE_CODE VARCHAR(20) NOT NULL COMMENT '역할 코드',
    PRIMARY KEY (MENU_ID, ROLE_CODE),
    FOREIGN KEY (MENU_ID) REFERENCES CMS_MENU(MENU_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_CODE) REFERENCES CMS_ROLE(ROLE_CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='역할별 메뉴 접근 권한';

-- CMS 접속 및 작업 감사 로그 테이블
CREATE TABLE CMS_ACCESS_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '로그 ID',
    ESNTL_ID VARCHAR(20) COMMENT '수행자 ID',
    CONECT_IP VARCHAR(50) COMMENT '접속 IP',
    CONECT_METHOD VARCHAR(10) COMMENT 'HTTP 메소드',
    CONECT_URL VARCHAR(255) COMMENT '접속 URL',
    LOG_CN LONGTEXT COMMENT '로그 상세(파라미터 등)',
    CREAT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '발생 시점',
    PRIMARY KEY (LOG_ID),
    INDEX (ESNTL_ID),
    INDEX (CREAT_PNTTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 접속 감사 로그';

-- 기초 데이터: 관리자 역할 및 초기 계정
INSERT INTO CMS_ROLE (ROLE_CODE, ROLE_NM, ROLE_DC) VALUES ('ROLE_ADMIN', '시스템 관리자', '시스템 전체 관리 권한');
INSERT INTO CMS_ROLE (ROLE_CODE, ROLE_NM, ROLE_DC) VALUES ('ROLE_EDITOR', '콘텐츠 편집자', '콘텐츠 작성 및 관리 권한');

INSERT INTO CMS_MEMBER (ESNTL_ID, MBER_ID, MBER_NM, PASSWORD, MBER_STTUS_CODE)
VALUES ('USR_0000000000001', 'admin', '최고 관리자', '$2a$10$7zB3pS.Hq.M8D.G9w7D9e.nS8W5WqWnN3B8zE7fWnQzE7fWnQzE7f', 'A');

INSERT INTO CMS_MEMBER_ROLE (ESNTL_ID, ROLE_CODE) VALUES ('USR_0000000000001', 'ROLE_ADMIN');

-- CMS 파일 그룹(마스터) 테이블
CREATE TABLE CMS_FILE_GROUP (
    ATCH_FILE_ID CHAR(20) NOT NULL COMMENT '첨부파일 ID',
    CREAT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시점',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    PRIMARY KEY (ATCH_FILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 파일 그룹 관리';

-- CMS 파일 상세 테이블
CREATE TABLE CMS_FILE_DETAIL (
    ATCH_FILE_ID CHAR(20) NOT NULL COMMENT '첨부파일 ID',
    FILE_SN INT NOT NULL COMMENT '파일 순번',
    FILE_STRE_COURS VARCHAR(2000) NOT NULL COMMENT '파일 저장 경로',
    STRE_FILE_NM VARCHAR(255) NOT NULL COMMENT '저장 파일 명',
    ORIGNL_FILE_NM VARCHAR(255) COMMENT '원본 파일 명',
    FILE_EXTSN VARCHAR(20) COMMENT '파일 확장자',
    FILE_CN TEXT COMMENT '파일 내용/설명',
    FILE_SIZE BIGINT COMMENT '파일 크기',
    THUMB_AT CHAR(1) DEFAULT 'N' COMMENT '썸네일 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (ATCH_FILE_ID, FILE_SN),
    FOREIGN KEY (ATCH_FILE_ID) REFERENCES CMS_FILE_GROUP(ATCH_FILE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 파일 상세 정보';

-- CMS 페이지뷰 통계 테이블
CREATE TABLE CMS_STATS_PV (
    STATS_ID BIGINT AUTO_INCREMENT COMMENT '통계 ID',
    CONECT_URL VARCHAR(500) NOT NULL COMMENT '접속 URL',
    ESNTL_ID VARCHAR(20) COMMENT '접속자 고유 ID',
    CONECT_IP VARCHAR(50) COMMENT '접속 IP',
    REFERER_URL VARCHAR(500) COMMENT '이전 페이지 URL',
    CONECT_DE CHAR(8) NOT NULL COMMENT '접속 일자(YYYYMMDD)',
    CREAT_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '기록 시점',
    PRIMARY KEY (STATS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 페이지뷰 통계';

-- CMS 게시판 마스터 테이블
CREATE TABLE CMS_BOARD_MASTER (
    BBS_ID CHAR(20) NOT NULL COMMENT '게시판 ID',
    BBS_NM VARCHAR(255) NOT NULL COMMENT '게시판 명',
    BBS_INTRCN VARCHAR(2400) COMMENT '게시판 소개',
    BBS_TY_CODE CHAR(6) NOT NULL COMMENT '게시판 유형 코드',
    REPLY_POSBL_AT CHAR(1) DEFAULT 'N' COMMENT '답장 가능 여부',
    FILE_ATCH_POSBL_AT CHAR(1) DEFAULT 'Y' COMMENT '파일 첨부 가능 여부',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (BBS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 게시판 마스터';

-- CMS 게시물 테이블
CREATE TABLE CMS_BOARD_POST (
    NTT_ID BIGINT AUTO_INCREMENT COMMENT '게시물 ID',
    BBS_ID CHAR(20) NOT NULL COMMENT '게시판 ID',
    NTT_SJ VARCHAR(2000) NOT NULL COMMENT '게시물 제목',
    NTT_CN MEDIUMTEXT COMMENT '게시물 내용',
    RDCNT INT DEFAULT 0 COMMENT '조회수',
    USE_AT CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    ATCH_FILE_ID CHAR(20) COMMENT '첨부파일 ID',
    FRST_REGISTER_ID VARCHAR(20) COMMENT '최초 등록자 ID',
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록 시점',
    PRIMARY KEY (NTT_ID),
    FOREIGN KEY (BBS_ID) REFERENCES CMS_BOARD_MASTER(BBS_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CMS 게시판 게시물';

-- 초기 게시판 데이터 (공지사항)
INSERT INTO CMS_BOARD_MASTER (BBS_ID, BBS_NM, BBS_INTRCN, BBS_TY_CODE) 
VALUES ('BBSMSTR_00000000001', '공지사항', '시스템 공지사항 게시판입니다.', 'BBST01');
